"""Versioned, read-only catalog access for sourced qPCR primer pairs.

The small JSON file bundled with the application is a reviewed seed set.  A
larger SQLite database generated by ``scripts/build_qpcr_catalog.py`` can be
mounted at ``QPCR_CATALOG_DB`` without changing the API or the frontend.
"""

from __future__ import annotations

import json
import logging
import sqlite3
from functools import lru_cache
from pathlib import Path

from app.core.config import settings
from app.schemas.gene_primer import (
    KnownPrimerCatalogResponse,
    KnownPrimerRecord,
    PrimerCatalogSnapshot,
    Species,
)

logger = logging.getLogger("uvicorn")
SEED_PATH = Path(__file__).resolve().parents[1] / "data" / "known_qpcr_primers.json"

EVIDENCE_PRIORITY = {
    "experimental_record": 0,
    "published_record": 1,
    "vendor_tested": 2,
    "database_record": 3,
    "computed_database": 4,
}


def _normalized(value: str) -> str:
    return value.strip().upper()


def _accession_root(value: str | None) -> str:
    return (value or "").strip().upper().split(".", 1)[0]


@lru_cache(maxsize=1)
def _seed_records() -> tuple[KnownPrimerRecord, ...]:
    payload = json.loads(SEED_PATH.read_text(encoding="utf-8"))
    return tuple(KnownPrimerRecord.model_validate(item) for item in payload)


def _catalog_path() -> Path | None:
    raw = settings.QPCR_CATALOG_DB.strip()
    if not raw:
        return None
    path = Path(raw).expanduser()
    return path if path.is_file() else None


def _connect(path: Path) -> sqlite3.Connection:
    # The production catalog is a completed snapshot mounted read-only.  Mark
    # it immutable so SQLite never tries to create WAL/SHM sidecar files in
    # the read-only reference-data mount.
    connection = sqlite3.connect(f"file:{path}?mode=ro&immutable=1", uri=True, timeout=3)
    connection.row_factory = sqlite3.Row
    return connection


def _record_from_row(row: sqlite3.Row) -> KnownPrimerRecord:
    return KnownPrimerRecord(
        id=row["record_id"],
        gene_symbol=row["gene_symbol"],
        species=row["species"],
        target_accession=row["target_accession"],
        forward_primer=row["forward_primer"],
        reverse_primer=row["reverse_primer"],
        source_name=row["source_name"],
        source_record_id=row["source_record_id"],
        source_url=row["source_url"],
        evidence=row["evidence"],
        evidence_url=row["evidence_url"],
        source_amplicon_size_bp=row["source_amplicon_size_bp"],
        source_forward_tm_c=row["source_forward_tm_c"],
        source_reverse_tm_c=row["source_reverse_tm_c"],
        retrieved_on=row["retrieved_on"],
        source_reference=row["source_reference"],
    )


def _deduplicate(records: list[KnownPrimerRecord], limit: int) -> list[KnownPrimerRecord]:
    seen: set[tuple[str, str]] = set()
    unique: list[KnownPrimerRecord] = []
    records.sort(
        key=lambda record: (
            EVIDENCE_PRIORITY.get(record.evidence.value, 99),
            record.source_name.lower(),
            record.source_record_id.lower(),
        )
    )
    for record in records:
        key = (_normalized(record.forward_primer), _normalized(record.reverse_primer))
        if key in seen:
            continue
        seen.add(key)
        unique.append(record)
        if len(unique) >= limit:
            break
    return unique


def query_known_primers(
    gene: str,
    species: Species,
    target_transcript: str | None = None,
    limit: int = 5,
) -> KnownPrimerCatalogResponse:
    """Return traceable source records without implying experimental validation."""

    normalized_query = _normalized(gene)
    resolved_symbol: str | None = None
    ncbi_gene_id: str | None = None
    gene_index_available = False
    gene_index_match = False
    catalog_gene_count = 0
    catalog_pair_count = 0
    snapshots: list[PrimerCatalogSnapshot] = []
    records: list[KnownPrimerRecord] = []

    catalog_path = _catalog_path()
    if catalog_path:
        try:
            with _connect(catalog_path) as db:
                gene_index_available = True
                gene_row = db.execute(
                    """
                    SELECT DISTINCT g.id, g.symbol, g.ncbi_gene_id
                    FROM genes AS g
                    LEFT JOIN gene_aliases AS a ON a.gene_id = g.id
                    WHERE g.species = ? AND (g.symbol_norm = ? OR a.alias_norm = ?)
                    ORDER BY CASE WHEN g.symbol_norm = ? THEN 0 ELSE 1 END, g.id
                    LIMIT 1
                    """,
                    (species.value, normalized_query, normalized_query, normalized_query),
                ).fetchone()
                if gene_row:
                    gene_index_match = True
                    resolved_symbol = gene_row["symbol"]
                    ncbi_gene_id = gene_row["ncbi_gene_id"]
                    target_root = _accession_root(target_transcript)
                    if target_root:
                        pair_rows = db.execute(
                            """
                            SELECT * FROM primer_pairs
                            WHERE species = ? AND (gene_id = ? OR target_accession_root = ?)
                            """,
                            (species.value, gene_row["id"], target_root),
                        ).fetchall()
                    else:
                        pair_rows = db.execute(
                            "SELECT * FROM primer_pairs WHERE species = ? AND gene_id = ?",
                            (species.value, gene_row["id"]),
                        ).fetchall()
                elif target_transcript:
                    pair_rows = db.execute(
                        "SELECT * FROM primer_pairs WHERE species = ? AND target_accession_root = ?",
                        (species.value, _accession_root(target_transcript)),
                    ).fetchall()
                else:
                    pair_rows = []

                for row in pair_rows:
                    record = _record_from_row(row)
                    if not record.gene_symbol and resolved_symbol:
                        record = record.model_copy(update={"gene_symbol": resolved_symbol})
                    records.append(record)
                catalog_gene_count = db.execute(
                    "SELECT COUNT(*) FROM genes WHERE species = ?", (species.value,)
                ).fetchone()[0]
                catalog_pair_count = db.execute(
                    "SELECT COUNT(*) FROM primer_pairs WHERE species = ?", (species.value,)
                ).fetchone()[0]
                snapshots = [
                    PrimerCatalogSnapshot(
                        source_name=row["source_name"],
                        release=row["release"],
                        imported_at=row["imported_at"],
                    )
                    for row in db.execute(
                        "SELECT source_name, release, imported_at FROM catalog_snapshots ORDER BY source_name"
                    ).fetchall()
                ]
        except (sqlite3.Error, OSError, ValueError) as exc:
            logger.warning("qPCR catalog unavailable: %s", exc)
            gene_index_available = False

    seed_symbols = {normalized_query}
    if resolved_symbol:
        seed_symbols.add(_normalized(resolved_symbol))
    target_root = _accession_root(target_transcript)
    for record in _seed_records():
        if record.species != species:
            continue
        if _normalized(record.gene_symbol) in seed_symbols or (
            target_root and _accession_root(record.target_accession) == target_root
        ):
            records.append(record)

    if not resolved_symbol and records:
        resolved_symbol = records[0].gene_symbol

    return KnownPrimerCatalogResponse(
        query=gene,
        species=species,
        resolved_gene_symbol=resolved_symbol,
        ncbi_gene_id=ncbi_gene_id,
        gene_index_available=gene_index_available,
        gene_index_match=gene_index_match,
        computed_design_available=True,
        records=_deduplicate(records, limit),
        catalog_gene_count=catalog_gene_count,
        catalog_pair_count=catalog_pair_count,
        snapshots=snapshots,
    )
