export type LocalizedText = {
  zh: string;
  en: string;
};

export type RecipeIngredient = {
  name: LocalizedText;
  amount: number;
  unit: "g" | "mL";
  chemicalId?: string;
};

export type SolutionRecipe = {
  id: string;
  title: LocalizedText;
  subtitle: LocalizedText;
  category: "buffer" | "electrophoresis" | "stock";
  defaultVolumeMl: number;
  ingredients: RecipeIngredient[];
  steps: LocalizedText[];
  notes: LocalizedText[];
  sourceLabel: string;
  sourceUrl: string;
  safetyQuery?: string;
};

export const SOLUTION_RECIPES: SolutionRecipe[] = [
  {
    id: "pbs-1x",
    title: { zh: "1× PBS（pH 7.4）", en: "1× PBS (pH 7.4)" },
    subtitle: {
      zh: "无钙、无镁的磷酸盐缓冲盐水",
      en: "Phosphate-buffered saline without calcium or magnesium",
    },
    category: "buffer",
    defaultVolumeMl: 1000,
    ingredients: [
      { name: { zh: "氯化钠（NaCl）", en: "Sodium chloride (NaCl)" }, amount: 8, unit: "g" },
      { name: { zh: "氯化钾（KCl）", en: "Potassium chloride (KCl)" }, amount: 0.2, unit: "g" },
      { name: { zh: "无水磷酸氢二钠（Na₂HPO₄）", en: "Anhydrous disodium phosphate (Na₂HPO₄)" }, amount: 1.44, unit: "g" },
      { name: { zh: "磷酸二氢钾（KH₂PO₄）", en: "Potassium phosphate monobasic (KH₂PO₄)" }, amount: 0.24, unit: "g" },
    ],
    steps: [
      { zh: "先将各组分溶于约 80% 终体积的去离子水。", en: "Dissolve the components in about 80% of the final volume of deionized water." },
      { zh: "测量并将 pH 调至 7.4，再用水定容。", en: "Measure and adjust to pH 7.4, then bring to final volume with water." },
      { zh: "根据实验用途选择过滤除菌或高压灭菌，并按实验室规定标注。", en: "Filter-sterilize or autoclave when appropriate for the application, then label under local laboratory rules." },
    ],
    notes: [
      { zh: "此配方按无水 Na₂HPO₄ 计算；若使用水合物，质量不能直接照抄。", en: "This formulation uses anhydrous Na₂HPO₄; do not reuse the listed mass for a hydrate." },
      { zh: "细胞培养等用途应核对具体体系对无菌、内毒素和离子组成的要求。", en: "For cell culture, verify sterility, endotoxin, and ionic-composition requirements for the specific application." },
    ],
    sourceLabel: "Thermo Fisher Scientific · PBS recipe",
    sourceUrl: "https://tools.thermofisher.com/content/sfs/manuals/293ebna_man.pdf",
  },
  {
    id: "tae-50x",
    title: { zh: "50× TAE", en: "50× TAE" },
    subtitle: {
      zh: "琼脂糖凝胶电泳浓缩液",
      en: "Concentrated buffer for agarose gel electrophoresis",
    },
    category: "electrophoresis",
    defaultVolumeMl: 1000,
    ingredients: [
      { name: { zh: "Tris 碱", en: "Tris base" }, amount: 242, unit: "g" },
      { name: { zh: "冰醋酸", en: "Glacial acetic acid" }, amount: 57.1, unit: "mL" },
      { name: { zh: "0.5 M EDTA（pH 8.0）", en: "0.5 M EDTA (pH 8.0)" }, amount: 100, unit: "mL" },
    ],
    steps: [
      { zh: "将 Tris 碱溶于约 60% 终体积的去离子水。", en: "Dissolve Tris base in about 60% of the final volume of deionized water." },
      { zh: "在合适的通风和防护条件下加入冰醋酸与 EDTA。", en: "Add glacial acetic acid and EDTA with appropriate ventilation and protective controls." },
      { zh: "混匀后用水定容；配制 1× 工作液时按 1:49 稀释。", en: "Mix and bring to final volume; dilute 1:49 to prepare a 1× working solution." },
    ],
    notes: [
      { zh: "大量 Tris 溶解和加酸可能放热；先留足定容空间并控制温度。", en: "Dissolving a large Tris mass and adding acid can release heat; leave headroom and control temperature." },
      { zh: "冰醋酸具有腐蚀性和挥发性，必须核对当前产品 SDS。", en: "Glacial acetic acid is corrosive and volatile; check the current product SDS." },
    ],
    sourceLabel: "Bio-Rad · Bulletin 6205",
    sourceUrl: "https://www.bio-rad.com/webroot/web/pdf/lsr/literature/Bulletin_6205.pdf",
    safetyQuery: "glacial acetic acid",
  },
  {
    id: "tbe-10x",
    title: { zh: "10× TBE", en: "10× TBE" },
    subtitle: {
      zh: "高缓冲容量的核酸电泳浓缩液",
      en: "High-capacity concentrated buffer for nucleic-acid electrophoresis",
    },
    category: "electrophoresis",
    defaultVolumeMl: 1000,
    ingredients: [
      { name: { zh: "Tris 碱", en: "Tris base" }, amount: 108, unit: "g" },
      { name: { zh: "硼酸", en: "Boric acid" }, amount: 55, unit: "g" },
      { name: { zh: "0.5 M EDTA（pH 8.0）", en: "0.5 M EDTA (pH 8.0)" }, amount: 40, unit: "mL" },
    ],
    steps: [
      { zh: "将 Tris 碱和硼酸溶于约 60% 终体积的去离子水。", en: "Dissolve Tris base and boric acid in about 60% of the final volume of deionized water." },
      { zh: "加入 0.5 M EDTA（pH 8.0），充分混匀。", en: "Add 0.5 M EDTA (pH 8.0) and mix thoroughly." },
      { zh: "用水定容；配制 1× 工作液时按 1:9 稀释。", en: "Bring to final volume; dilute 1:9 to prepare a 1× working solution." },
    ],
    notes: [
      { zh: "TBE 缓冲容量较强，适合较长或较高电压的电泳；具体条件仍以实验体系为准。", en: "TBE has greater buffering capacity for longer or higher-voltage runs; confirm conditions for the specific system." },
      { zh: "含硼酸废液的处置遵循机构规定，不直接套用普通水溶液废弃流程。", en: "Dispose of borate-containing waste under institutional rules rather than treating it as ordinary aqueous waste." },
    ],
    sourceLabel: "Bio-Rad · Bulletin 6205",
    sourceUrl: "https://www.bio-rad.com/webroot/web/pdf/lsr/literature/Bulletin_6205.pdf",
    safetyQuery: "boric acid",
  },
  {
    id: "tris-hcl-1m-ph8",
    title: { zh: "1 M Tris-HCl（pH 8.0）", en: "1 M Tris-HCl (pH 8.0)" },
    subtitle: { zh: "常用分子生物学缓冲储备液", en: "Common molecular-biology buffer stock" },
    category: "stock",
    defaultVolumeMl: 1000,
    ingredients: [
      { name: { zh: "Tris 碱", en: "Tris base" }, amount: 121.14, unit: "g" },
    ],
    steps: [
      { zh: "将 Tris 碱溶于约 80% 终体积的去离子水。", en: "Dissolve Tris base in about 80% of the final volume of deionized water." },
      { zh: "在搅拌、通风和适当防护下，用 HCl 缓慢调至 pH 8.0。", en: "With stirring, ventilation, and appropriate protection, slowly adjust to pH 8.0 with HCl." },
      { zh: "溶液回到目标温度后复核 pH，再用水定容。", en: "After the solution returns to the target temperature, recheck pH and bring to final volume." },
    ],
    notes: [
      { zh: "Tris 的 pH 对温度敏感；记录校准温度，不要先定容再大量加酸。", en: "Tris pH is temperature-sensitive; record the calibration temperature and do not make to volume before substantial acid addition." },
      { zh: "所需 HCl 体积取决于浓度和实际滴定，不能由本页面给出固定值。", en: "The HCl volume depends on its concentration and the actual titration; this page intentionally does not prescribe a fixed amount." },
    ],
    sourceLabel: "Thermo Fisher Scientific · 1 M Tris buffers",
    sourceUrl: "https://documents.thermofisher.com/TFS-Assets/LSG/manuals/sp_9851.pdf",
    safetyQuery: "HCl",
  },
  {
    id: "sds-10-percent",
    title: { zh: "10% SDS（w/v）", en: "10% SDS (w/v)" },
    subtitle: { zh: "十二烷基硫酸钠储备液", en: "Sodium dodecyl sulfate stock solution" },
    category: "stock",
    defaultVolumeMl: 100,
    ingredients: [
      { name: { zh: "SDS", en: "SDS" }, amount: 10, unit: "g" },
    ],
    steps: [
      { zh: "避免扬尘，将 SDS 缓慢加入约 80% 终体积的水中。", en: "Avoid generating dust and slowly add SDS to about 80% of the final volume of water." },
      { zh: "轻柔搅拌至溶解，尽量避免大量泡沫。", en: "Stir gently until dissolved while minimizing foam." },
      { zh: "用水定容并按实验室规定标注。", en: "Bring to final volume with water and label under local laboratory rules." },
    ],
    notes: [
      { zh: "SDS 粉尘可刺激呼吸道和眼睛；配制前核对供应商 SDS。", en: "SDS dust can irritate the respiratory tract and eyes; check the supplier SDS before preparation." },
      { zh: "10% w/v 表示每 100 mL 终体积含 10 g SDS，不是加入 100 mL 水。", en: "10% w/v means 10 g SDS per 100 mL final volume, not 10 g added to 100 mL water." },
    ],
    sourceLabel: "Thermo Fisher Scientific · standalone reagent recipes",
    sourceUrl: "https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-gel-electrophoresis/protein-gels/protein-gel-casting-cassettes.html",
    safetyQuery: "SDS",
  },
];

export type HazardCategory = "acute" | "corrosive" | "flammable" | "oxidizer" | "chronic" | "irritant";
export type ChemicalUse = "nucleic-acid" | "protein" | "cell-culture" | "histology" | "general" | "cleaning";
export type ChemicalMaterialType = "substance" | "solution" | "mixture" | "product";

export type ChemicalSafetyRecord = {
  id: string;
  name: LocalizedText;
  aliases: string[];
  cas: string;
  formula: string;
  cid?: number;
  sourceUrl?: string;
  sourceLabel?: LocalizedText;
  uses?: ChemicalUse[];
  materialType?: ChemicalMaterialType;
  level: "critical" | "high" | "moderate";
  signal: LocalizedText;
  categories: HazardCategory[];
  ghs: Array<{ code: string; statement: LocalizedText }>;
  summary: LocalizedText;
  controls: LocalizedText[];
  incompatibilities: LocalizedText;
  special: LocalizedText;
};

export type ChemicalInteractionAlert = {
  id: string;
  title: LocalizedText;
  reagents: LocalizedText;
  summary: LocalizedText;
  response: LocalizedText;
  sourceLabel: string;
  sourceUrl: string;
};

export const CHEMICAL_SAFETY_RECORDS: ChemicalSafetyRecord[] = [
  {
    id: "acrylamide",
    uses: ["protein"],
    name: { zh: "丙烯酰胺", en: "Acrylamide" },
    aliases: ["79-06-1", "2-propenamide", "丙烯酰胺"],
    cas: "79-06-1",
    formula: "C₃H₅NO",
    cid: 6579,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "chronic", "irritant"],
    ghs: [
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H340", statement: { zh: "可能导致遗传性缺陷", en: "May cause genetic defects" } },
      { code: "H350", statement: { zh: "可能致癌", en: "May cause cancer" } },
      { code: "H372", statement: { zh: "长期或反复接触会损害器官", en: "Causes organ damage through prolonged or repeated exposure" } },
    ],
    summary: {
      zh: "未聚合的丙烯酰胺单体可经吞咽、吸入粉尘或皮肤接触造成危害，并具有遗传毒性和致癌性分类。",
      en: "Unpolymerized acrylamide monomer is hazardous by ingestion, dust inhalation, and skin contact, with mutagenicity and carcinogenicity classifications.",
    },
    controls: [
      { zh: "优先使用预制溶液或预制凝胶，减少称量单体粉末。", en: "Prefer premade solutions or gels to reduce handling of monomer powder." },
      { zh: "称量和转移粉末应使用经风险评估的局部排风，并避免任何皮肤接触。", en: "Weigh and transfer powder under risk-assessed local exhaust controls and prevent skin contact." },
    ],
    incompatibilities: { zh: "强氧化剂；受热或不当条件下可能发生聚合。", en: "Strong oxidizers; heat or unsuitable conditions can initiate polymerization." },
    special: { zh: "聚丙烯酰胺凝胶与未聚合单体的风险不同；不要将两者混为一谈。", en: "Polyacrylamide gel and unpolymerized monomer do not have the same hazard profile; do not treat them as equivalent." },
  },
  {
    id: "formaldehyde",
    uses: ["cell-culture", "histology"],
    materialType: "solution",
    name: { zh: "甲醛 / 福尔马林", en: "Formaldehyde / formalin" },
    aliases: ["50-00-0", "formalin", "methanal", "甲醛", "福尔马林"],
    cas: "50-00-0",
    formula: "CH₂O",
    cid: 712,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive", "chronic", "irritant"],
    ghs: [
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H317", statement: { zh: "可能导致皮肤过敏反应", en: "May cause an allergic skin reaction" } },
      { code: "H331", statement: { zh: "吸入中毒", en: "Toxic if inhaled" } },
      { code: "H350", statement: { zh: "可能致癌", en: "May cause cancer" } },
    ],
    summary: {
      zh: "甲醛蒸气可刺激并损伤眼、皮肤和呼吸道；其致癌与致敏风险要求在受控通风下操作。",
      en: "Formaldehyde vapor can irritate and damage the eyes, skin, and respiratory tract; its carcinogenic and sensitizing hazards require controlled ventilation.",
    },
    controls: [
      { zh: "开盖、分装和固定操作应在合格通风柜或机构批准的局部排风中进行。", en: "Open-container transfer and fixation work should be performed in a certified hood or institution-approved local exhaust." },
      { zh: "福尔马林常含甲醇；可燃性和毒性必须以当前配方 SDS 为准。", en: "Formalin often contains methanol; use the current formulation SDS for flammability and toxicity." },
    ],
    incompatibilities: { zh: "强氧化剂、强酸、强碱；具体配方可能含其他稳定剂。", en: "Strong oxidizers, strong acids, and strong bases; formulations may contain additional stabilizers." },
    special: { zh: "“甲醛气体”“甲醛水溶液”和不同浓度福尔马林并非同一个危险标签。", en: "Formaldehyde gas, aqueous formaldehyde, and formalin concentrations do not share one identical hazard label." },
  },
  {
    id: "phenol",
    uses: ["nucleic-acid", "protein"],
    name: { zh: "苯酚", en: "Phenol" },
    aliases: ["108-95-2", "carbolic acid", "hydroxybenzene", "苯酚"],
    cas: "108-95-2",
    formula: "C₆H₆O",
    cid: 996,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive", "chronic"],
    ghs: [
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H311", statement: { zh: "皮肤接触中毒", en: "Toxic in contact with skin" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H341", statement: { zh: "怀疑导致遗传性缺陷", en: "Suspected of causing genetic defects" } },
    ],
    summary: {
      zh: "苯酚具有腐蚀性，并可迅速经皮肤吸收产生全身毒性；局部麻醉感可能掩盖组织损伤。",
      en: "Phenol is corrosive and can be rapidly absorbed through skin with systemic toxicity; local numbing can mask tissue injury.",
    },
    controls: [
      { zh: "在通风柜中操作，并依据供应商 SDS 的渗透数据选择手套，不默认普通一次性手套足够。", en: "Work in a fume hood and select gloves using permeation data in the supplier SDS; do not assume ordinary disposable gloves are sufficient." },
      { zh: "操作前确认洗眼器、安全淋浴与实验室苯酚暴露应急流程可用。", en: "Before work, confirm access to eyewash, safety shower, and the laboratory phenol-exposure procedure." },
    ],
    incompatibilities: { zh: "强氧化剂；避免与不相容金属和材料接触，详见产品 SDS 第 10 节。", en: "Strong oxidizers; avoid incompatible metals and materials listed in Section 10 of the product SDS." },
    special: { zh: "苯酚/氯仿混合液必须按混合物 SDS 管理，不能只看单一成分。", en: "Phenol/chloroform mixtures must be managed using the mixture SDS, not a single-ingredient record." },
  },
  {
    id: "chloroform",
    uses: ["nucleic-acid"],
    name: { zh: "氯仿", en: "Chloroform" },
    aliases: ["67-66-3", "trichloromethane", "CHCl3", "氯仿", "三氯甲烷"],
    cas: "67-66-3",
    formula: "CHCl₃",
    cid: 6212,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "chronic", "irritant"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H331", statement: { zh: "吸入中毒", en: "Toxic if inhaled" } },
      { code: "H351", statement: { zh: "怀疑致癌", en: "Suspected of causing cancer" } },
      { code: "H372", statement: { zh: "长期或反复接触会损害器官", en: "Causes organ damage through prolonged or repeated exposure" } },
    ],
    summary: {
      zh: "氯仿蒸气有急性吸入毒性，长期暴露可损害器官，并具有疑似致癌分类。",
      en: "Chloroform vapor presents acute inhalation toxicity, can damage organs after repeated exposure, and carries a suspected-carcinogen classification.",
    },
    controls: [
      { zh: "所有开口操作均在通风柜中进行，容器及时密闭。", en: "Perform all open-container work in a fume hood and close containers promptly." },
      { zh: "多种常见手套对氯仿的突破时间很短；必须按 SDS/兼容性表选材并制定更换频率。", en: "Many common gloves have short breakthrough times for chloroform; select materials and change intervals from SDS/compatibility data." },
    ],
    incompatibilities: { zh: "强碱、强氧化剂、部分活泼金属；光和空气可促进危险分解，稳定剂类型会影响管理。", en: "Strong bases, strong oxidizers, and some reactive metals; light and air can promote hazardous decomposition, and stabilizer choice affects handling." },
    special: { zh: "不要用气味判断暴露是否安全，也不要在普通台面长时间敞口操作。", en: "Do not use odor to judge safe exposure and do not leave chloroform open on the bench." },
  },
  {
    id: "methanol",
    uses: ["protein", "histology", "general"],
    name: { zh: "甲醇", en: "Methanol" },
    aliases: ["67-56-1", "methyl alcohol", "MeOH", "甲醇"],
    cas: "67-56-1",
    formula: "CH₄O",
    cid: 887,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "flammable", "chronic"],
    ghs: [
      { code: "H225", statement: { zh: "高度易燃液体和蒸气", en: "Highly flammable liquid and vapor" } },
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H311", statement: { zh: "皮肤接触中毒", en: "Toxic in contact with skin" } },
      { code: "H370", statement: { zh: "会损害器官", en: "Causes damage to organs" } },
    ],
    summary: {
      zh: "甲醇高度易燃，可经吞咽、吸入和皮肤接触导致严重中毒，典型靶器官包括视觉系统和中枢神经系统。",
      en: "Methanol is highly flammable and can cause severe poisoning through ingestion, inhalation, or skin contact, with the visual and central nervous systems among key targets.",
    },
    controls: [
      { zh: "远离火花、热源和明火；大量或易产生蒸气的操作在通风柜中完成。", en: "Keep away from sparks, heat, and flames; perform large-volume or vapor-generating work in a hood." },
      { zh: "废液置于合规的易燃有机废液容器，不倒入下水道。", en: "Collect waste in an approved flammable-organic waste container; do not drain-dispose." },
    ],
    incompatibilities: { zh: "强氧化剂与点火源。", en: "Strong oxidizers and ignition sources." },
    special: { zh: "中毒症状可能延迟；任何疑似暴露都应立即启动急救和医学评估。", en: "Poisoning symptoms can be delayed; any suspected exposure warrants immediate first-aid response and medical evaluation." },
  },
  {
    id: "ethanol",
    uses: ["cell-culture", "general", "cleaning"],
    name: { zh: "乙醇", en: "Ethanol" },
    aliases: ["64-17-5", "ethyl alcohol", "EtOH", "乙醇", "酒精"],
    cas: "64-17-5",
    formula: "C₂H₆O",
    cid: 702,
    level: "moderate",
    signal: { zh: "危险", en: "Danger" },
    categories: ["flammable", "irritant"],
    ghs: [
      { code: "H225", statement: { zh: "高度易燃液体和蒸气", en: "Highly flammable liquid and vapor" } },
      { code: "H319", statement: { zh: "造成严重眼刺激", en: "Causes serious eye irritation" } },
    ],
    summary: {
      zh: "实验室浓乙醇的首要危险是高度易燃，蒸气可被远处点火源引燃；高浓度也可造成明显眼刺激。",
      en: "The primary laboratory hazard of concentrated ethanol is high flammability; vapor can ignite at a remote source, and concentrated product can seriously irritate eyes.",
    },
    controls: [
      { zh: "控制台面用量，远离热源、电火花和明火，按易燃液体要求储存。", en: "Limit bench quantities, keep away from heat, sparks, and flames, and store as a flammable liquid." },
      { zh: "70% 等水溶液仍可能易燃；不能因稀释就省略标签和储存评估。", en: "Aqueous formulations such as 70% can remain flammable; dilution does not remove labeling or storage assessment." },
    ],
    incompatibilities: { zh: "强氧化剂与点火源。", en: "Strong oxidizers and ignition sources." },
    special: { zh: "变性乙醇含有其他成分，毒性必须看该产品的 SDS，不能套用纯乙醇条目。", en: "Denatured ethanol contains additional chemicals; use that product's SDS rather than this pure-ethanol record." },
  },
  {
    id: "acetic-acid",
    uses: ["nucleic-acid", "protein", "general"],
    name: { zh: "乙酸 / 冰醋酸", en: "Acetic acid / glacial acetic acid" },
    aliases: ["64-19-7", "acetic acid", "glacial acetic acid", "ethanoic acid", "乙酸", "醋酸", "冰醋酸"],
    cas: "64-19-7",
    formula: "C₂H₄O₂",
    cid: 176,
    level: "high",
    signal: { zh: "危险", en: "Danger" },
    categories: ["corrosive", "flammable"],
    ghs: [
      { code: "H226", statement: { zh: "易燃液体和蒸气", en: "Flammable liquid and vapor" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
    ],
    summary: {
      zh: "冰醋酸具有腐蚀性和可燃性，挥发性蒸气可造成严重刺激；稀释放热并可能飞溅。",
      en: "Glacial acetic acid is corrosive and flammable, with strongly irritating vapor; dilution releases heat and can splash.",
    },
    controls: [
      { zh: "开盖、转移和浓液配制在通风柜中进行，并按飞溅风险使用眼面部防护。", en: "Open, transfer, and prepare concentrated material in a fume hood with eye/face protection matched to splash risk." },
      { zh: "稀释时将酸缓慢加入水中并搅拌冷却，远离点火源。", en: "For dilution, slowly add acid to water with stirring and cooling, away from ignition sources." },
    ],
    incompatibilities: { zh: "强氧化剂、强碱和多种活泼金属；按产品 SDS 第 10 节分区储存。", en: "Strong oxidizers, strong bases, and many reactive metals; segregate using Section 10 of the product SDS." },
    special: { zh: "冰醋酸与低浓度乙酸溶液的危险标签不同；配方中的体积必须对应正确纯度。", en: "Glacial acetic acid and dilute solutions do not carry identical labels; recipe volumes must match the specified purity." },
  },
  {
    id: "boric-acid",
    uses: ["nucleic-acid"],
    name: { zh: "硼酸", en: "Boric acid" },
    aliases: ["10043-35-3", "orthoboric acid", "boracic acid", "硼酸"],
    cas: "10043-35-3",
    formula: "H₃BO₃",
    cid: 7628,
    level: "high",
    signal: { zh: "危险", en: "Danger" },
    categories: ["chronic"],
    ghs: [
      { code: "H360FD", statement: { zh: "可能损害生育能力；可能对胎儿造成伤害", en: "May damage fertility; may damage the unborn child" } },
    ],
    summary: {
      zh: "硼酸具有生殖毒性分类。称量粉末和配制高浓度储备液时应尽量减少粉尘与人员暴露。",
      en: "Boric acid carries a reproductive-toxicity classification. Minimize dust and personal exposure when weighing powder or preparing concentrated stocks.",
    },
    controls: [
      { zh: "避免产生粉尘，在经风险评估的局部排风下称量并及时清洁残留。", en: "Avoid dust generation, weigh under risk-assessed local exhaust, and clean residues promptly." },
      { zh: "涉及孕期、生育计划或职业暴露关注时，遵循机构 EHS 的专项评估与替代要求。", en: "For pregnancy, fertility planning, or occupational-exposure concerns, follow institution-specific EHS assessment and substitution requirements." },
    ],
    incompatibilities: { zh: "不在无验证方案下与其他试剂混合；按当前产品 SDS 第 10 节确认不相容物。", en: "Do not combine outside a validated procedure; use Section 10 of the current product SDS for incompatibilities." },
    special: { zh: "“毒性较低”的经验印象不能替代其生殖毒性分类和本机构的暴露控制。", en: "A reputation for low acute toxicity does not override its reproductive classification or institutional exposure controls." },
  },
  {
    id: "sodium-dodecyl-sulfate",
    uses: ["protein", "nucleic-acid"],
    name: { zh: "十二烷基硫酸钠（SDS）", en: "Sodium dodecyl sulfate (SDS)" },
    aliases: ["151-21-3", "sodium lauryl sulfate", "SDS", "SLS", "十二烷基硫酸钠"],
    cas: "151-21-3",
    formula: "C₁₂H₂₅NaO₄S",
    cid: 3423265,
    level: "high",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "irritant"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H315", statement: { zh: "造成皮肤刺激", en: "Causes skin irritation" } },
      { code: "H318", statement: { zh: "造成严重眼损伤", en: "Causes serious eye damage" } },
      { code: "H335", statement: { zh: "可能引起呼吸道刺激", en: "May cause respiratory irritation" } },
    ],
    summary: {
      zh: "SDS 粉末可刺激呼吸道，且对眼睛具有严重损伤风险；配液时的主要控制点是避免扬尘和飞溅。",
      en: "SDS powder can irritate the respiratory tract and presents a serious eye-damage hazard; dust and splash prevention are the key controls during solution preparation.",
    },
    controls: [
      { zh: "缓慢加粉、轻柔搅拌，使用经风险评估的局部排风并佩戴合适眼部防护。", en: "Add powder slowly, stir gently, and use risk-assessed local exhaust with appropriate eye protection." },
      { zh: "及时清理粉末残留，避免用会再次扬尘的方式干扫。", en: "Clean powder residues promptly without dry-sweeping methods that re-aerosolize dust." },
    ],
    incompatibilities: { zh: "强氧化剂；按当前产品 SDS 第 10 节确认储存分区。", en: "Strong oxidizers; confirm storage segregation in Section 10 of the current product SDS." },
    special: { zh: "配成溶液会降低粉尘风险，但不会自动消除眼刺激、皮肤刺激或废液管理要求。", en: "Preparing a solution reduces dust risk but does not automatically remove eye, skin, or waste-management hazards." },
  },
  {
    id: "hydrochloric-acid",
    uses: ["general"],
    name: { zh: "盐酸", en: "Hydrochloric acid" },
    aliases: ["7647-01-0", "HCl", "muriatic acid", "盐酸", "氯化氢"],
    cas: "7647-01-0",
    formula: "HCl",
    cid: 313,
    level: "high",
    signal: { zh: "危险", en: "Danger" },
    categories: ["corrosive", "irritant"],
    ghs: [
      { code: "H290", statement: { zh: "可能腐蚀金属", en: "May be corrosive to metals" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H335", statement: { zh: "可能引起呼吸道刺激", en: "May cause respiratory irritation" } },
    ],
    summary: {
      zh: "浓盐酸具有强腐蚀性并释放刺激性氯化氢蒸气；危险分类会随浓度变化。",
      en: "Concentrated hydrochloric acid is strongly corrosive and releases irritating hydrogen chloride vapor; classification changes with concentration.",
    },
    controls: [
      { zh: "浓酸开盖、转移和调 pH 在通风柜中进行，并根据飞溅风险配置眼面部防护。", en: "Open, transfer, and use concentrated acid for pH adjustment in a fume hood, with eye/face protection matched to splash risk." },
      { zh: "稀释时把酸缓慢加入水中并搅拌冷却，切勿把水倒入浓酸。", en: "For dilution, slowly add acid to water with stirring and cooling; never add water to concentrated acid." },
    ],
    incompatibilities: { zh: "碱、活泼金属、氧化剂；与氰化物或硫化物接触可释放高毒气体。", en: "Bases, reactive metals, and oxidizers; contact with cyanides or sulfides can release highly toxic gases." },
    special: { zh: "本条目的 H290/H314/H335 更接近常见浓盐酸溶液；氯化氢气体有不同分类。", en: "The H290/H314/H335 summary is representative of common concentrated solutions; hydrogen chloride gas has a different classification." },
  },
  {
    id: "sodium-hydroxide",
    uses: ["general", "cleaning"],
    name: { zh: "氢氧化钠", en: "Sodium hydroxide" },
    aliases: ["1310-73-2", "NaOH", "caustic soda", "氢氧化钠", "烧碱"],
    cas: "1310-73-2",
    formula: "NaOH",
    cid: 14798,
    level: "high",
    signal: { zh: "危险", en: "Danger" },
    categories: ["corrosive"],
    ghs: [
      { code: "H290", statement: { zh: "可能腐蚀金属", en: "May be corrosive to metals" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
    ],
    summary: {
      zh: "氢氧化钠固体和浓溶液具有强腐蚀性；溶解和稀释时大量放热，可造成沸腾与飞溅。",
      en: "Solid and concentrated sodium hydroxide are strongly corrosive; dissolution and dilution release substantial heat and can cause boiling or splashing.",
    },
    controls: [
      { zh: "将 NaOH 少量、缓慢加入水中并持续搅拌冷却；不要把水直接倒在大量固体上。", en: "Add NaOH to water slowly in small portions with continuous stirring and cooling; do not pour water directly onto a large mass of solid." },
      { zh: "根据浓度、规模和飞溅风险使用护目镜、面屏及耐化学腐蚀防护。", en: "Use goggles, face protection, and chemically resistant PPE appropriate to concentration, scale, and splash risk." },
    ],
    incompatibilities: { zh: "酸；铝、锌等金属可能释放可燃氢气；与部分有机物反应。", en: "Acids; metals such as aluminum and zinc can release flammable hydrogen; reacts with some organic materials." },
    special: { zh: "低浓度溶液与固体/浓碱的标签不同，仍应按实际产品和浓度查 SDS。", en: "Dilute solutions do not share the same label as solid or concentrated base; always use the actual product and concentration SDS." },
  },
  {
    id: "guanidine-thiocyanate",
    uses: ["nucleic-acid"],
    name: { zh: "异硫氰酸胍", en: "Guanidine thiocyanate" },
    aliases: ["593-84-0", "guanidinium thiocyanate", "guanidine isothiocyanate", "GITC", "GuSCN", "异硫氰酸胍"],
    cas: "593-84-0",
    formula: "C₂H₆N₄S",
    cid: 65046,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive", "irritant"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H312", statement: { zh: "皮肤接触有害", en: "Harmful in contact with skin" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H332", statement: { zh: "吸入有害", en: "Harmful if inhaled" } },
    ],
    summary: { zh: "核酸裂解液中的常见变性剂；粉尘、浓溶液和飞溅可经吞咽、皮肤或吸入造成危害。", en: "A common chaotrope in nucleic-acid lysis buffers; dust, concentrated solution, and splashes can be harmful by ingestion, skin contact, or inhalation." },
    controls: [
      { zh: "称量粉末和处理浓缩液时使用经风险评估的局部排风，避免扬尘和飞溅。", en: "Use risk-assessed local exhaust for powder weighing and concentrated solutions; prevent dust and splashes." },
      { zh: "含胍废液单独收集并清楚标识，执行试剂盒或产品 SDS 的废弃流程。", en: "Collect guanidinium-containing waste separately, label it clearly, and follow the kit or product SDS waste procedure." },
    ],
    incompatibilities: { zh: "次氯酸盐漂白剂和酸性溶液；不得直接加入含异硫氰酸胍的废液。", en: "Hypochlorite bleach and acidic solutions; never add them directly to guanidine-thiocyanate waste." },
    special: { zh: "异硫氰酸胍、盐酸胍和含胍商品裂解液不是同一个物质或配方，必须分别查 SDS。", en: "Guanidine thiocyanate, guanidine hydrochloride, and commercial guanidinium lysis buffers are not the same substance or formulation; check each SDS separately." },
  },
  {
    id: "guanidine-hydrochloride",
    uses: ["nucleic-acid", "protein"],
    name: { zh: "盐酸胍", en: "Guanidine hydrochloride" },
    aliases: ["50-01-1", "guanidinium chloride", "guanidine HCl", "GuHCl", "GdnHCl", "盐酸胍"],
    cas: "50-01-1",
    formula: "CH₆ClN₃",
    cid: 5742,
    level: "high",
    signal: { zh: "警告", en: "Warning" },
    categories: ["acute", "irritant"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H315", statement: { zh: "造成皮肤刺激", en: "Causes skin irritation" } },
      { code: "H319", statement: { zh: "造成严重眼刺激", en: "Causes serious eye irritation" } },
    ],
    summary: { zh: "常用于蛋白变性和核酸纯化；粉末及高浓度溶液可造成吞咽危害和皮肤、眼刺激。", en: "Used for protein denaturation and nucleic-acid purification; powder and concentrated solutions can be harmful if swallowed and irritate skin and eyes." },
    controls: [
      { zh: "减少粉尘，称量后及时清洁天平和工作面。", en: "Minimize dust and clean the balance and work surface promptly after weighing." },
      { zh: "配液和废弃时按实际浓度、添加剂及供应商 SDS 评估。", en: "Assess preparation and disposal using the actual concentration, additives, and supplier SDS." },
    ],
    incompatibilities: { zh: "强氧化剂；具体不相容物以产品 SDS 第 10 节为准。", en: "Strong oxidizers; use Section 10 of the product SDS for formulation-specific incompatibilities." },
    special: { zh: "不要把异硫氰酸胍的漂白剂禁忌机械套用到所有胍盐，但任何商品裂解液仍须查其配方 SDS。", en: "Do not mechanically transfer the bleach warning for guanidine thiocyanate to every guanidinium salt, but always check the formulation SDS for commercial lysis buffers." },
  },
  {
    id: "beta-mercaptoethanol",
    uses: ["nucleic-acid", "protein"],
    name: { zh: "β-巯基乙醇", en: "2-Mercaptoethanol" },
    aliases: ["60-24-2", "beta-mercaptoethanol", "β-mercaptoethanol", "BME", "2-ME", "2-mercaptoethanol", "巯基乙醇"],
    cas: "60-24-2",
    formula: "C₂H₆OS",
    cid: 1567,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive", "irritant"],
    ghs: [
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H310/H311", statement: { zh: "皮肤接触可致命或中毒", en: "Fatal or toxic in contact with skin" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H317", statement: { zh: "可能导致皮肤过敏反应", en: "May cause an allergic skin reaction" } },
    ],
    summary: { zh: "挥发性还原剂，可经吸入、吞咽和皮肤吸收造成严重危害；气味不能作为安全暴露指标。", en: "A volatile reducing agent that can cause severe harm by inhalation, ingestion, and skin absorption; odor is not a safe exposure indicator." },
    controls: [
      { zh: "开盖、移液和加入裂解液时在通风柜中操作，使用二次容器。", en: "Open, pipette, and add to lysis buffers in a fume hood, using secondary containment." },
      { zh: "依据实际产品 SDS 的渗透数据选择手套并规定更换频率。", en: "Select gloves and change intervals from permeation data for the actual product SDS." },
    ],
    incompatibilities: { zh: "强氧化剂和部分金属；受热可产生有毒硫氧化物。", en: "Strong oxidizers and some metals; heating can generate toxic sulfur oxides." },
    special: { zh: "闻不到或已经习惯气味不代表空气浓度安全。", en: "Not noticing the odor, or becoming accustomed to it, does not indicate a safe airborne concentration." },
  },
  {
    id: "dithiothreitol",
    uses: ["nucleic-acid", "protein"],
    name: { zh: "二硫苏糖醇（DTT）", en: "Dithiothreitol (DTT)" },
    aliases: ["3483-12-3", "dithiothreitol", "Cleland reagent", "DTT", "二硫苏糖醇"],
    cas: "3483-12-3",
    formula: "C₄H₁₀O₂S₂",
    cid: 439196,
    level: "high",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "irritant"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H315", statement: { zh: "造成皮肤刺激", en: "Causes skin irritation" } },
      { code: "H318", statement: { zh: "造成严重眼损伤", en: "Causes serious eye damage" } },
      { code: "H335", statement: { zh: "可能引起呼吸道刺激", en: "May cause respiratory irritation" } },
    ],
    summary: { zh: "常用还原剂；粉末的主要风险是吞咽、眼损伤及皮肤和呼吸道刺激。", en: "A common reducing agent; powder hazards include harmful ingestion, serious eye damage, and skin or respiratory irritation." },
    controls: [
      { zh: "避免扬尘并佩戴合适眼部防护；优先使用已验证浓度的预制溶液。", en: "Avoid dust and use appropriate eye protection; prefer validated premade solutions where practical." },
      { zh: "配置小份储备液并清楚标注浓度、溶剂、日期和储存条件。", en: "Prepare small stock aliquots and label concentration, solvent, date, and storage condition." },
    ],
    incompatibilities: { zh: "强氧化剂；具体储存和反应性按产品 SDS。", en: "Strong oxidizers; follow the product SDS for storage and reactivity details." },
    special: { zh: "溶液降低粉尘风险，但溶剂和浓度可能改变整体危险分类。", en: "A solution reduces dust risk, but solvent and concentration can change the overall hazard classification." },
  },
  {
    id: "trizol-reagent",
    uses: ["nucleic-acid"],
    materialType: "product",
    name: { zh: "TRIzol 类 RNA 提取试剂", en: "TRIzol-type RNA extraction reagent" },
    aliases: ["TRIzol", "TRIzol LS", "phenol guanidine thiocyanate", "AGPC", "酸性酚异硫氰酸胍"],
    cas: "—",
    formula: "Mixture",
    sourceUrl: "https://documents.thermofisher.com/TFS-Assets/LSG/SDS/15596026_MTR-NALT_EN.pdf",
    sourceLabel: { zh: "Thermo Fisher TRIzol 产品 SDS", en: "Thermo Fisher TRIzol product SDS" },
    level: "critical",
    signal: { zh: "按产品 SDS", en: "Check product SDS" },
    categories: ["acute", "corrosive", "chronic"],
    ghs: [],
    summary: { zh: "含酚和异硫氰酸胍的商品混合物；危险取决于具体配方，不能用单一成分条目替代产品 SDS。", en: "A commercial mixture containing phenol and guanidine thiocyanate; hazards depend on the exact formulation and cannot be represented by a single ingredient record." },
    controls: [
      { zh: "开盖、匀浆、分相和废液转移在通风柜中完成，并防止皮肤接触。", en: "Perform opening, homogenization, phase separation, and waste transfer in a fume hood and prevent skin contact." },
      { zh: "为含酚/胍废液设置独立、兼容、清楚标识的废液容器。", en: "Use a separate, compatible, clearly labeled waste container for phenol/guanidinium waste." },
    ],
    incompatibilities: { zh: "不要向试剂或样品制备废液直接加入漂白剂或酸性溶液。", en: "Do not add bleach or acidic solutions directly to the reagent or sample-preparation waste." },
    special: { zh: "不同品牌和版本的 RNA 裂解试剂不是同一配方；每次以瓶身和当前产品 SDS 为准。", en: "RNA lysis reagents from different brands or versions are not one formulation; use the container label and current product SDS each time." },
  },
  {
    id: "ethidium-bromide",
    uses: ["nucleic-acid"],
    name: { zh: "溴化乙锭（EtBr）", en: "Ethidium bromide (EtBr)" },
    aliases: ["1239-45-8", "ethidium bromide", "EtBr", "homidium bromide", "溴化乙锭"],
    cas: "1239-45-8",
    formula: "C₂₁H₂₀BrN₃",
    cid: 14710,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "chronic"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H330", statement: { zh: "吸入致命", en: "Fatal if inhaled" } },
      { code: "H341", statement: { zh: "怀疑导致遗传性缺陷", en: "Suspected of causing genetic defects" } },
    ],
    summary: { zh: "DNA 嵌入染料；粉末吸入危险和疑似致突变分类使称量、污染控制与废弃管理成为重点。", en: "A DNA-intercalating dye whose powder inhalation hazard and suspected-mutagen classification make weighing, contamination control, and waste management critical." },
    controls: [
      { zh: "优先使用预制溶液，指定操作区域和专用托盘，避免处理干粉。", en: "Prefer premade solutions and use a designated area and dedicated tray to avoid handling dry powder." },
      { zh: "建立凝胶、缓冲液、耗材和污染物的机构批准废弃流程。", en: "Use an institution-approved waste stream for gels, buffers, disposables, and contaminated materials." },
    ],
    incompatibilities: { zh: "强氧化剂；按实际产品 SDS 管理溶剂、储存和废弃。", en: "Strong oxidizers; manage solvent, storage, and disposal using the actual product SDS." },
    special: { zh: "“替代染料”不自动等于无害；SYBR Safe、GelRed 等必须查看各自产品 SDS。", en: "An alternative dye is not automatically harmless; SYBR Safe, GelRed, and similar products require their own SDS review." },
  },
  {
    id: "temed",
    uses: ["protein"],
    name: { zh: "TEMED", en: "TEMED" },
    aliases: ["110-18-9", "tetramethylethylenediamine", "N,N,N',N'-tetramethylethylenediamine", "TEMED", "四甲基乙二胺"],
    cas: "110-18-9",
    formula: "C₆H₁₆N₂",
    cid: 8037,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive", "flammable"],
    ghs: [
      { code: "H225", statement: { zh: "高度易燃液体和蒸气", en: "Highly flammable liquid and vapor" } },
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H332", statement: { zh: "吸入有害", en: "Harmful if inhaled" } },
    ],
    summary: { zh: "聚丙烯酰胺凝胶聚合促进剂；挥发、易燃且具有腐蚀和急性毒性危险。", en: "A polyacrylamide polymerization accelerator that is volatile, highly flammable, corrosive, and acutely hazardous." },
    controls: [
      { zh: "在通风柜中小量移液，远离火花、热源和明火，容器立即密闭。", en: "Pipette small quantities in a fume hood, keep away from sparks, heat, and flames, and close the container immediately." },
      { zh: "按易燃腐蚀性液体的实际 SDS 确认储存分区和泄漏处置。", en: "Use the actual SDS to determine storage segregation and spill response for this flammable corrosive liquid." },
    ],
    incompatibilities: { zh: "强氧化剂、酸和点火源。", en: "Strong oxidizers, acids, and ignition sources." },
    special: { zh: "TEMED 与 APS 是经过验证的聚合体系，但各自的储存和废弃要求不能互相替代。", en: "TEMED and APS form a validated polymerization system, but each retains separate storage and disposal requirements." },
  },
  {
    id: "ammonium-persulfate",
    uses: ["protein"],
    name: { zh: "过硫酸铵（APS）", en: "Ammonium persulfate (APS)" },
    aliases: ["7727-54-0", "ammonium peroxydisulfate", "APS", "过硫酸铵"],
    cas: "7727-54-0",
    formula: "(NH₄)₂S₂O₈",
    cid: 62648,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "oxidizer", "irritant"],
    ghs: [
      { code: "H272", statement: { zh: "可能加剧燃烧；氧化剂", en: "May intensify fire; oxidizer" } },
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H317", statement: { zh: "可能导致皮肤过敏反应", en: "May cause an allergic skin reaction" } },
      { code: "H334", statement: { zh: "吸入可能导致过敏或哮喘症状", en: "May cause allergy or asthma symptoms if inhaled" } },
    ],
    summary: { zh: "强氧化剂和呼吸道/皮肤致敏物；粉末称量与远离可燃物是主要控制点。", en: "A strong oxidizer and respiratory/skin sensitizer; powder control and segregation from combustibles are central precautions." },
    controls: [
      { zh: "避免扬尘并使用合适局部排风；有哮喘或致敏症状时立即停止并报告。", en: "Avoid dust with appropriate local exhaust; stop work and report any asthma or sensitization symptoms." },
      { zh: "保持容器清洁干燥，避免有机物、还原剂或其他可燃物污染。", en: "Keep the container clean and dry and prevent contamination by organics, reducing agents, or other combustibles." },
    ],
    incompatibilities: { zh: "还原剂、有机物和可燃材料；作为氧化剂需分区储存。", en: "Reducing agents, organics, and combustible materials; segregate in oxidizer storage." },
    special: { zh: "新鲜 APS 溶液用于聚合并不消除其氧化性和致敏风险。", en: "Using fresh APS solution for polymerization does not remove its oxidizing or sensitizing hazards." },
  },
  {
    id: "bisacrylamide",
    uses: ["protein"],
    name: { zh: "N,N′-亚甲基双丙烯酰胺", en: "N,N′-Methylenebisacrylamide" },
    aliases: ["110-26-9", "bisacrylamide", "BIS", "MBAA", "methylene bisacrylamide", "双丙烯酰胺"],
    cas: "110-26-9",
    formula: "C₇H₁₀N₂O₂",
    cid: 8041,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "chronic", "irritant"],
    ghs: [
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H312", statement: { zh: "皮肤接触有害", en: "Harmful in contact with skin" } },
      { code: "H340", statement: { zh: "可能导致遗传性缺陷", en: "May cause genetic defects" } },
    ],
    summary: { zh: "聚丙烯酰胺凝胶交联剂；未聚合粉末具有急性毒性和遗传毒性分类。", en: "A polyacrylamide gel crosslinker; the unpolymerized powder carries acute-toxicity and germ-cell-mutagenicity classifications." },
    controls: [
      { zh: "优先使用预混丙烯酰胺/双丙烯酰胺溶液，减少称量干粉。", en: "Prefer premixed acrylamide/bisacrylamide solutions to reduce dry-powder handling." },
      { zh: "指定聚合区域，及时去污，并区分单体废物与完全聚合凝胶。", en: "Designate a polymerization area, decontaminate promptly, and distinguish monomer waste from fully polymerized gels." },
    ],
    incompatibilities: { zh: "强氧化剂；受热或引发条件下可聚合。", en: "Strong oxidizers; heat or initiators can promote polymerization." },
    special: { zh: "完全聚合凝胶与未聚合单体的危险不同，但废弃仍须遵循机构规定。", en: "Fully polymerized gels differ from unpolymerized monomer, but disposal still follows institutional rules." },
  },
  {
    id: "pmsf",
    uses: ["protein"],
    name: { zh: "PMSF", en: "PMSF" },
    aliases: ["329-98-6", "phenylmethylsulfonyl fluoride", "phenylmethanesulfonyl fluoride", "PMSF", "苯甲基磺酰氟"],
    cas: "329-98-6",
    formula: "C₇H₇FO₂S",
    cid: 4784,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive"],
    ghs: [
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
    ],
    summary: { zh: "丝氨酸蛋白酶抑制剂；粉末和高浓度储备液具有急性毒性及腐蚀危险。", en: "A serine-protease inhibitor whose powder and concentrated stocks present acute toxicity and corrosive hazards." },
    controls: [
      { zh: "避免称量粉尘；在通风和二次容器下制备小份储备液。", en: "Avoid powder dust and prepare small stock aliquots with ventilation and secondary containment." },
      { zh: "同时评估常用储备液溶剂（如异丙醇或乙醇）的易燃性。", en: "Also assess the flammability of common stock solvents such as isopropanol or ethanol." },
    ],
    incompatibilities: { zh: "强碱、强氧化剂和水分；以实际产品 SDS 第 10 节为准。", en: "Strong bases, strong oxidizers, and moisture; confirm in Section 10 of the actual product SDS." },
    special: { zh: "PMSF 水溶液不稳定并不意味着降解后即可作为普通废液处理。", en: "Instability of PMSF in water does not mean degraded solutions can be treated as ordinary waste." },
  },
  {
    id: "paraformaldehyde",
    uses: ["cell-culture", "histology"],
    name: { zh: "多聚甲醛（PFA）", en: "Paraformaldehyde (PFA)" },
    aliases: ["30525-89-4", "paraformaldehyde", "PFA", "polyoxymethylene", "paraform", "多聚甲醛"],
    cas: "30525-89-4",
    formula: "(CH₂O)ₙ",
    sourceUrl: "https://www.thermofisher.com/order/catalog/product/es/en/416780250",
    sourceLabel: { zh: "Thermo Scientific 多聚甲醛产品与 SDS", en: "Thermo Scientific paraformaldehyde product and SDS" },
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "flammable", "chronic", "irritant"],
    ghs: [
      { code: "H228", statement: { zh: "易燃固体", en: "Flammable solid" } },
      { code: "H302/H332", statement: { zh: "吞咽或吸入有害", en: "Harmful if swallowed or inhaled" } },
      { code: "H317", statement: { zh: "可能导致皮肤过敏反应", en: "May cause an allergic skin reaction" } },
      { code: "H351", statement: { zh: "怀疑致癌", en: "Suspected of causing cancer" } },
    ],
    summary: { zh: "可释放甲醛的聚合固体；粉末、加热溶解和高浓度溶液需要通风及暴露控制。", en: "A polymeric solid that releases formaldehyde; powder, heated dissolution, and concentrated solutions require ventilation and exposure controls." },
    controls: [
      { zh: "不要在普通开放台面称量或加热溶解；使用机构批准的通风和固定液配制流程。", en: "Do not weigh or heat-dissolve on an open bench; use institution-approved ventilation and fixative preparation procedures." },
      { zh: "操作前确认甲醛暴露、泄漏和废液应急流程。", en: "Confirm formaldehyde exposure, spill, and waste procedures before work." },
    ],
    incompatibilities: { zh: "强氧化剂、强酸和强碱；受热可释放甲醛蒸气。", en: "Strong oxidizers, strong acids, and strong bases; heating can release formaldehyde vapor." },
    special: { zh: "PFA 固体、4% PFA 固定液和福尔马林的组成与危险标签不同。", en: "Solid PFA, 4% PFA fixative, and formalin have different compositions and hazard labels." },
  },
  {
    id: "glutaraldehyde",
    uses: ["cell-culture", "histology", "cleaning"],
    materialType: "solution",
    name: { zh: "戊二醛", en: "Glutaraldehyde" },
    aliases: ["111-30-8", "glutaral", "pentane-1,5-dial", "glutaraldehyde", "戊二醛"],
    cas: "111-30-8",
    formula: "C₅H₈O₂",
    cid: 3485,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "corrosive", "irritant"],
    ghs: [
      { code: "H301", statement: { zh: "吞咽中毒", en: "Toxic if swallowed" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H330", statement: { zh: "吸入致命", en: "Fatal if inhaled" } },
      { code: "H334", statement: { zh: "吸入可能导致过敏或哮喘症状", en: "May cause allergy or asthma symptoms if inhaled" } },
    ],
    summary: { zh: "固定剂和消毒剂；挥发性暴露可造成严重刺激、腐蚀以及呼吸道和皮肤致敏。", en: "A fixative and disinfectant whose vapor exposure can cause severe irritation, corrosion, and respiratory or skin sensitization." },
    controls: [
      { zh: "开盖、浸泡、倾倒和废液转移使用有效局部排风或密闭系统。", en: "Use effective local exhaust or a closed system for opening, soaking, pouring, and waste transfer." },
      { zh: "出现喘鸣、胸闷或皮疹时立即停止操作并按职业健康流程报告。", en: "Stop work and follow occupational-health reporting for wheeze, chest tightness, or rash." },
    ],
    incompatibilities: { zh: "强氧化剂、强酸和强碱；不同浓度和活化配方按产品 SDS 管理。", en: "Strong oxidizers, strong acids, and strong bases; manage different concentrations and activated formulations by product SDS." },
    special: { zh: "低浓度消毒配方不等于无挥发或无致敏风险。", en: "A diluted disinfectant formulation is not automatically free of vapor or sensitization risk." },
  },
  {
    id: "trypan-blue",
    uses: ["cell-culture"],
    materialType: "solution",
    name: { zh: "台盼蓝", en: "Trypan blue" },
    aliases: ["72-57-1", "trypan blue stain", "C.I. Direct Blue 14", "台盼蓝", "锥虫蓝"],
    cas: "72-57-1",
    formula: "C₃₄H₂₄N₆Na₄O₁₄S₄",
    cid: 6296,
    sourceUrl: "https://documents.thermofisher.com/TFS-Assets/LSG/SDS/15250061_MTR-NALT_EN.pdf",
    sourceLabel: { zh: "Thermo Fisher 台盼蓝染液 SDS", en: "Thermo Fisher Trypan Blue Stain SDS" },
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["chronic"],
    ghs: [
      { code: "H350", statement: { zh: "可能致癌", en: "May cause cancer" } },
      { code: "H361", statement: { zh: "怀疑损害生育能力或胎儿", en: "Suspected of damaging fertility or the unborn child" } },
    ],
    summary: { zh: "常见细胞活率染料；示例商品染液 SDS 将其归为致癌和生殖毒性关注物，实际浓度与配方必须逐瓶核对。", en: "A common viability dye; the example commercial stain SDS classifies it for carcinogenic and reproductive hazards, so each concentration and formulation must be checked." },
    controls: [
      { zh: "避免气溶胶和皮肤接触，使用封闭废液容器并控制移液污染。", en: "Avoid aerosols and skin contact, use a closed waste container, and control pipetting contamination." },
      { zh: "粉末、0.4% 染液和其他商品浓度按各自 SDS 处理。", en: "Treat powder, 0.4% stain, and other commercial concentrations according to their own SDS." },
    ],
    incompatibilities: { zh: "强氧化剂；按产品 SDS 和机构染料废物流程处置。", en: "Strong oxidizers; dispose under the product SDS and institutional dye-waste procedure." },
    special: { zh: "不要因为使用量小或是细胞计数试剂就把它当作普通水溶液。", en: "Do not treat it as an ordinary aqueous solution merely because the working volume is small or it is used for cell counting." },
  },
  {
    id: "dapi",
    uses: ["cell-culture", "histology"],
    name: { zh: "DAPI（二盐酸盐）", en: "DAPI dihydrochloride" },
    aliases: ["28718-90-3", "4',6-diamidino-2-phenylindole", "DAPI", "DAPI dihydrochloride", "二盐酸DAPI"],
    cas: "28718-90-3",
    formula: "C₁₆H₁₇Cl₂N₅",
    sourceUrl: "https://documents.thermofisher.com/TFS-Assets/LSG/SDS/D1306_MTR-NALT_EN.pdf",
    sourceLabel: { zh: "Thermo Fisher DAPI 二盐酸盐 SDS", en: "Thermo Fisher DAPI dihydrochloride SDS" },
    level: "moderate",
    signal: { zh: "无信号词", en: "No signal word" },
    categories: [],
    ghs: [],
    summary: { zh: "示例 DAPI 二盐酸盐产品 SDS 未将其列为 GHS 危险物，但同时指出毒理性质尚未被充分研究。", en: "The example DAPI dihydrochloride SDS does not classify the product as GHS hazardous, while noting that its toxicological properties have not been thoroughly investigated." },
    controls: [
      { zh: "仍按实验室化学品谨慎操作，避免粉末、皮肤接触和不必要的气溶胶。", en: "Continue prudent laboratory handling and avoid powder, skin contact, and unnecessary aerosols." },
      { zh: "现配溶液、封片剂和试剂盒可能含不同溶剂或添加剂，必须查具体产品 SDS。", en: "Prepared solutions, mounting media, and kits may contain different solvents or additives and require their own SDS." },
    ],
    incompatibilities: { zh: "示例 SDS 未报告已知危险反应；其他配方以产品 SDS 第 10 节为准。", en: "The example SDS reports no known hazardous reaction; use Section 10 of the actual SDS for other formulations." },
    special: { zh: "“未分类为危险”不等于已经证明无毒，尤其不能替代对未知危害的谨慎控制。", en: "Not classified as hazardous is not proof of no toxicity and does not replace prudent control of unknown hazards." },
  },
  {
    id: "hoechst-33342",
    uses: ["cell-culture", "histology"],
    name: { zh: "Hoechst 33342", en: "Hoechst 33342" },
    aliases: ["23491-52-3", "bisbenzimide", "Hoechst 33342", "HOE 33342", "赫斯特33342"],
    cas: "23491-52-3",
    formula: "C₂₇H₂₈N₆O",
    cid: 1464,
    level: "critical",
    signal: { zh: "警告", en: "Warning" },
    categories: ["acute", "chronic", "irritant"],
    ghs: [
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H315", statement: { zh: "造成皮肤刺激", en: "Causes skin irritation" } },
      { code: "H335", statement: { zh: "可能引起呼吸道刺激", en: "May cause respiratory irritation" } },
      { code: "H341", statement: { zh: "怀疑导致遗传性缺陷", en: "Suspected of causing genetic defects" } },
    ],
    summary: { zh: "可透细胞的 DNA 结合染料；代表性分类包括刺激和疑似致突变危险。", en: "A cell-permeant DNA-binding dye with representative classifications for irritation and suspected germ-cell mutagenicity." },
    controls: [
      { zh: "优先使用低量预制溶液，避免称量粉末并控制染色废液。", en: "Prefer low-volume premade solutions, avoid powder weighing, and control staining waste." },
      { zh: "进行活细胞实验不代表该染料对操作人员无害。", en: "Suitability for live-cell experiments does not mean the dye is harmless to the operator." },
    ],
    incompatibilities: { zh: "强氧化剂；溶剂和盐型按实际产品 SDS。", en: "Strong oxidizers; use the actual product SDS for solvent and salt form." },
    special: { zh: "Hoechst 33342 粉末、DMSO 储备液和即用型产品的危险标签可能不同。", en: "Hoechst 33342 powder, DMSO stock, and ready-to-use products can carry different hazard labels." },
  },
  {
    id: "isopropanol",
    uses: ["nucleic-acid", "cell-culture", "general", "cleaning"],
    name: { zh: "异丙醇", en: "Isopropanol" },
    aliases: ["67-63-0", "isopropyl alcohol", "2-propanol", "IPA", "异丙醇"],
    cas: "67-63-0",
    formula: "C₃H₈O",
    cid: 3776,
    level: "moderate",
    signal: { zh: "危险", en: "Danger" },
    categories: ["flammable", "irritant"],
    ghs: [
      { code: "H225", statement: { zh: "高度易燃液体和蒸气", en: "Highly flammable liquid and vapor" } },
      { code: "H319", statement: { zh: "造成严重眼刺激", en: "Causes serious eye irritation" } },
      { code: "H336", statement: { zh: "可能引起困倦或眩晕", en: "May cause drowsiness or dizziness" } },
    ],
    summary: { zh: "核酸沉淀和消毒常用溶剂；大量蒸气、远处点火源和密闭空间是主要风险。", en: "A common solvent for nucleic-acid precipitation and disinfection; vapor accumulation, remote ignition sources, and confined spaces are key risks." },
    controls: [
      { zh: "限制台面用量并远离火花、热源和明火；大量使用时确保有效通风。", en: "Limit bench quantities and keep away from sparks, heat, and flames; ensure effective ventilation for larger use." },
      { zh: "按易燃液体储存和收集废液，不用普通冰箱储存大量易燃溶剂。", en: "Store and collect as a flammable liquid; do not use an ordinary refrigerator for bulk flammable solvent." },
    ],
    incompatibilities: { zh: "强氧化剂和点火源。", en: "Strong oxidizers and ignition sources." },
    special: { zh: "70% 异丙醇仍可易燃；消毒用途不会取消易燃液体管理要求。", en: "70% isopropanol can remain flammable; disinfectant use does not remove flammable-liquid controls." },
  },
  {
    id: "acetone",
    uses: ["general", "histology", "cleaning"],
    name: { zh: "丙酮", en: "Acetone" },
    aliases: ["67-64-1", "propanone", "dimethyl ketone", "acetone", "丙酮"],
    cas: "67-64-1",
    formula: "C₃H₆O",
    cid: 180,
    level: "moderate",
    signal: { zh: "危险", en: "Danger" },
    categories: ["flammable", "irritant"],
    ghs: [
      { code: "H225", statement: { zh: "高度易燃液体和蒸气", en: "Highly flammable liquid and vapor" } },
      { code: "H319", statement: { zh: "造成严重眼刺激", en: "Causes serious eye irritation" } },
      { code: "H336", statement: { zh: "可能引起困倦或眩晕", en: "May cause drowsiness or dizziness" } },
    ],
    summary: { zh: "挥发快且高度易燃；清洁和固定用途常导致开放台面蒸气暴露与着火风险被低估。", en: "A fast-evaporating, highly flammable solvent whose bench cleaning and fixation use can lead to underestimated vapor and ignition risks." },
    controls: [
      { zh: "只取所需小量，立即密闭，远离点火源并保持通风。", en: "Dispense only the needed quantity, close promptly, keep away from ignition sources, and maintain ventilation." },
      { zh: "废擦拭物和废液放入机构指定的易燃溶剂废物容器。", en: "Place solvent wipes and waste liquid in institution-designated flammable-solvent waste containers." },
    ],
    incompatibilities: { zh: "强氧化剂、强酸和强碱；远离点火源。", en: "Strong oxidizers, strong acids, strong bases, and ignition sources." },
    special: { zh: "“很快挥发”会增加空气中蒸气，不代表残留自动安全。", en: "Rapid evaporation increases airborne vapor and does not make residues automatically safe." },
  },
  {
    id: "acetonitrile",
    uses: ["general", "protein", "nucleic-acid"],
    name: { zh: "乙腈", en: "Acetonitrile" },
    aliases: ["75-05-8", "methyl cyanide", "cyanomethane", "ACN", "MeCN", "乙腈"],
    cas: "75-05-8",
    formula: "C₂H₃N",
    cid: 6342,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "flammable", "irritant"],
    ghs: [
      { code: "H225", statement: { zh: "高度易燃液体和蒸气", en: "Highly flammable liquid and vapor" } },
      { code: "H302", statement: { zh: "吞咽有害", en: "Harmful if swallowed" } },
      { code: "H312", statement: { zh: "皮肤接触有害", en: "Harmful in contact with skin" } },
      { code: "H332", statement: { zh: "吸入有害", en: "Harmful if inhaled" } },
    ],
    summary: { zh: "HPLC/质谱和肽处理常用溶剂；高度易燃，可经吸入、皮肤和吞咽造成急性危害。", en: "A common HPLC/MS and peptide-processing solvent that is highly flammable and acutely harmful by inhalation, skin contact, and ingestion." },
    controls: [
      { zh: "配制流动相和收集仪器废液时保持通风，确认废液瓶密闭和液位。", en: "Maintain ventilation during mobile-phase preparation and instrument waste collection; verify waste-bottle closure and fill level." },
      { zh: "软管、接头和废液容器必须与乙腈兼容并远离点火源。", en: "Tubing, fittings, and waste containers must be acetonitrile-compatible and kept from ignition sources." },
    ],
    incompatibilities: { zh: "强氧化剂、强酸、强碱和点火源。", en: "Strong oxidizers, strong acids, strong bases, and ignition sources." },
    special: { zh: "HPLC 废液是混合物，分类和处置必须考虑全部流动相与样品成分。", en: "HPLC waste is a mixture; classification and disposal must account for all mobile-phase and sample components." },
  },
  {
    id: "dimethylformamide",
    uses: ["cell-culture", "general"],
    name: { zh: "N,N-二甲基甲酰胺（DMF）", en: "N,N-Dimethylformamide (DMF)" },
    aliases: ["68-12-2", "dimethylformamide", "N,N-dimethylformamide", "DMF", "二甲基甲酰胺"],
    cas: "68-12-2",
    formula: "C₃H₇NO",
    cid: 6228,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "chronic", "irritant"],
    ghs: [
      { code: "H312", statement: { zh: "皮肤接触有害", en: "Harmful in contact with skin" } },
      { code: "H319", statement: { zh: "造成严重眼刺激", en: "Causes serious eye irritation" } },
      { code: "H332", statement: { zh: "吸入有害", en: "Harmful if inhaled" } },
      { code: "H360D", statement: { zh: "可能损害胎儿", en: "May damage the unborn child" } },
    ],
    summary: { zh: "高渗透性溶剂，可经皮肤和吸入暴露，并具有生殖毒性分类。", en: "A highly penetrating solvent with dermal and inhalation exposure hazards and a reproductive-toxicity classification." },
    controls: [
      { zh: "使用通风柜并特别防止皮肤接触；手套须依据 DMF 渗透数据选择。", en: "Use a fume hood and prevent skin contact; select gloves using DMF-specific permeation data." },
      { zh: "按机构对生殖毒性物质的指定区域、培训和人员保护要求操作。", en: "Follow institutional designated-area, training, and personnel-protection requirements for reproductive toxins." },
    ],
    incompatibilities: { zh: "强氧化剂、强酸和强碱；与部分卤代试剂可发生危险反应。", en: "Strong oxidizers, strong acids, and strong bases; hazardous reactions can occur with some halogenating agents." },
    special: { zh: "DMF 可穿透多种常见手套，不能仅凭“戴了手套”判断防护有效。", en: "DMF can permeate many common gloves; wearing gloves alone does not demonstrate effective protection." },
  },
  {
    id: "sodium-hypochlorite",
    uses: ["cell-culture", "cleaning", "general"],
    materialType: "solution",
    name: { zh: "次氯酸钠 / 漂白液", en: "Sodium hypochlorite / bleach" },
    aliases: ["7681-52-9", "sodium hypochlorite", "NaOCl", "bleach", "次氯酸钠", "漂白水", "84消毒液"],
    cas: "7681-52-9",
    formula: "NaOCl",
    cid: 23665760,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["corrosive", "oxidizer", "irritant"],
    ghs: [
      { code: "H290", statement: { zh: "可能腐蚀金属", en: "May be corrosive to metals" } },
      { code: "H314", statement: { zh: "造成严重皮肤灼伤和眼损伤", en: "Causes severe skin burns and eye damage" } },
      { code: "H400", statement: { zh: "对水生生物毒性极大", en: "Very toxic to aquatic life" } },
    ],
    summary: { zh: "常见消毒剂和氧化剂；浓度、pH 与配方决定腐蚀性，错误混合可快速释放有毒气体。", en: "A common disinfectant and oxidizer whose corrosivity depends on concentration, pH, and formulation; incompatible mixing can rapidly release toxic gases." },
    controls: [
      { zh: "只按验证过的 SOP 稀释，保持通风，标签注明有效浓度和配制日期。", en: "Dilute only under a validated SOP with ventilation and label the active concentration and preparation date." },
      { zh: "使用前确认待处理表面或废液中不存在酸、氨或含胍裂解试剂。", en: "Before use, confirm the surface or waste contains no acid, ammonia, or guanidinium lysis reagent." },
    ],
    incompatibilities: { zh: "酸、氨/铵盐、异硫氰酸胍、还原剂和多种有机物。", en: "Acids, ammonia/ammonium salts, guanidine thiocyanate, reducing agents, and many organics." },
    special: { zh: "家用漂白液、实验室次氯酸钠和不同有效氯浓度不是同一标签，且会随储存时间降解。", en: "Household bleach, laboratory hypochlorite, and different available-chlorine concentrations do not share one label and degrade during storage." },
  },
  {
    id: "sodium-azide",
    uses: ["protein", "cell-culture", "general"],
    name: { zh: "叠氮化钠", en: "Sodium azide" },
    aliases: ["26628-22-8", "sodium azide", "NaN3", "NaN₃", "叠氮化钠"],
    cas: "26628-22-8",
    formula: "NaN₃",
    cid: 33557,
    level: "critical",
    signal: { zh: "危险", en: "Danger" },
    categories: ["acute", "chronic"],
    ghs: [
      { code: "H300", statement: { zh: "吞咽致命", en: "Fatal if swallowed" } },
      { code: "H400", statement: { zh: "对水生生物毒性极大", en: "Very toxic to aquatic life" } },
      { code: "H410", statement: { zh: "对水生生物毒性极大并具有长期持续影响", en: "Very toxic to aquatic life with long lasting effects" } },
    ],
    summary: { zh: "常作为抗体和缓冲液防腐剂；具有高度急性毒性，并可与酸或重金属形成额外危险。", en: "Used as a preservative in antibody and buffer solutions; it is highly acutely toxic and can create additional hazards with acids or heavy metals." },
    controls: [
      { zh: "使用最小可行量，避免粉尘和皮肤接触，并设置明确的含叠氮化物废液。", en: "Use the smallest practical amount, prevent dust and skin contact, and maintain a clearly designated azide waste stream." },
      { zh: "不要倒入下水道；核对管路中的铜、铅、银等材料。", en: "Do not drain-dispose and assess plumbing for copper, lead, silver, and similar metals." },
    ],
    incompatibilities: { zh: "酸可生成有毒、易爆的叠氮酸；铜、铅、银、汞等可形成对冲击敏感的金属叠氮化物。", en: "Acids can generate toxic, explosive hydrazoic acid; copper, lead, silver, mercury, and similar metals can form shock-sensitive metal azides." },
    special: { zh: "低浓度防腐剂废液仍可能在金属排水系统中长期累积，不能按普通缓冲液排放。", en: "Low-concentration preservative waste can still accumulate in metal drain systems and must not be treated as ordinary buffer waste." },
  },
];

export const CHEMICAL_INTERACTION_ALERTS: ChemicalInteractionAlert[] = [
  {
    id: "guanidinium-bleach",
    title: { zh: "含胍裂解废液 + 漂白剂或酸", en: "Guanidinium lysis waste + bleach or acid" },
    reagents: { zh: "TRIzol / 异硫氰酸胍 × 次氯酸盐 / 酸", en: "TRIzol / guanidine thiocyanate × hypochlorite / acid" },
    summary: { zh: "可能形成反应性物质和有毒气体。不要把漂白剂直接加入含异硫氰酸胍的试剂或样品制备废液。", en: "Reactive compounds and toxic gases may form. Never add bleach directly to guanidine-thiocyanate reagent or sample-preparation waste." },
    response: { zh: "单独收集、清楚标识，并执行产品 SDS 和机构危废流程。", en: "Collect separately, label clearly, and follow the product SDS and institutional hazardous-waste procedure." },
    sourceLabel: "Thermo Fisher · TRIzol Plus protocol",
    sourceUrl: "https://www.thermofisher.com/fr/en/home/references/protocols/nucleic-acid-purification-and-analysis/mrna-protocols/trizol-plus-rna-purification-kit.html",
  },
  {
    id: "hypochlorite-acid-ammonia",
    title: { zh: "漂白剂 + 酸或含氨试剂", en: "Bleach + acid or ammonia-containing reagent" },
    reagents: { zh: "次氯酸钠 × 酸 / 氨 / 铵盐", en: "Sodium hypochlorite × acid / ammonia / ammonium salt" },
    summary: { zh: "不相容混合会释放危险气体；不要用漂白剂处理成分不明的化学废液。", en: "Incompatible mixing can release hazardous gases; do not use bleach on chemically unidentified waste." },
    response: { zh: "停止混合并按实验室气体释放/泄漏应急流程撤离和报告。", en: "Stop mixing and follow the laboratory gas-release/spill procedure for evacuation and reporting." },
    sourceLabel: "PubChem · Sodium hypochlorite LCSS",
    sourceUrl: "https://pubchem.ncbi.nlm.nih.gov/compound/23665760",
  },
  {
    id: "azide-acid-metals",
    title: { zh: "叠氮化钠 + 酸或重金属管路", en: "Sodium azide + acid or heavy-metal plumbing" },
    reagents: { zh: "叠氮化钠 × 酸 / 铜 / 铅 / 银 / 汞", en: "Sodium azide × acid / copper / lead / silver / mercury" },
    summary: { zh: "酸可生成叠氮酸，金属可形成对冲击敏感的叠氮化物；含叠氮化物溶液不得排入下水道。", en: "Acids can generate hydrazoic acid and metals can form shock-sensitive azides; azide solutions must not be drain-disposed." },
    response: { zh: "使用专用相容废液容器，并让 EHS 评估历史排放或疑似沉积。", en: "Use a dedicated compatible waste container and have EHS assess historical discharge or suspected deposits." },
    sourceLabel: "PubChem · Sodium azide LCSS",
    sourceUrl: "https://pubchem.ncbi.nlm.nih.gov/compound/33557",
  },
];

export const PUBCHEM_GHS_URL = "https://pubchem.ncbi.nlm.nih.gov/ghs/ghs_10.html";
export const OSHA_SDS_URL = "https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200";
